# frozen_string_literal: true

require "helper"
require "tmpdir"

describe "agentdocs template" do
  let(:project_root) { ::File.expand_path("..", __dir__) }
  let(:geometry_doc_dir) { ::File.join(project_root, "examples/geometry/doc") }
  let(:rdoc_doc_dir) { ::File.join(project_root, "examples/rdoc/doc") }

  # Pinned `generated:` values for the `bundle.md` frontmatter, so the
  # byte-exact fixture comparison survives both the clock and a release bump.
  # The template's own defaults (`Time.now` and the real VERSION) are what
  # ships; only these two options are overridden here.
  let(:generated_by) { "yard-agentdocs/0.0.0" }
  let(:generated_at) { ::Time.utc(2026, 1, 1) }

  # Builds a Yardoc CLI with the pinned `generated:` options already set.
  # They have to be assigned before #run, which never resets the options
  # object it was given at construction.
  def yardoc_cli
    cli = ::YARD::CLI::Yardoc.new
    cli.options[:agentdocs_generated_by] = generated_by
    cli.options[:agentdocs_generated_at] = generated_at
    cli
  end

  # Runs from the project root so recorded source paths (used in "Defined in"
  # lines) come out relative, matching the examples/geometry/doc fixtures.
  def generate(output_dir)
    ::YARD::Registry.clear
    ::Dir.chdir(project_root) do
      files = ::Dir.glob("examples/geometry/lib/**/*.rb")
      yardoc_cli.run(
        "--no-yardopts", "--no-save", "--no-stats",
        "-o", output_dir,
        "-t", "default",
        "-f", "agentdocs",
        "--markup", "markdown",
        "--title", "yard-agentdocs example — API Reference",
        "--readme", "examples/geometry/README.md",
        "--files", "examples/geometry/docs/point_cloud.md",
        *files
      )
    end
  end

  # A small, separate fixture run with `--markup rdoc`, covering the
  # `:rdoc`-dialect path end to end (see "Docstring markup dialect" in
  # docs/dev/DESIGN.md) without coupling the main markdown-dialect fixture
  # set above to the installed rdoc gem's exact conversion output.
  def generate_rdoc(output_dir)
    ::YARD::Registry.clear
    ::Dir.chdir(project_root) do
      files = ::Dir.glob("examples/rdoc/lib/**/*.rb")
      yardoc_cli.run(
        "--no-yardopts", "--no-save", "--no-stats",
        "-o", output_dir,
        "-t", "default",
        "-f", "agentdocs",
        "--markup", "rdoc",
        "--title", "yard-agentdocs rdoc-dialect fixture — API Reference",
        "--readme", "examples/rdoc/README.rdoc",
        *files
      )
    end
  end

  # All regular file paths under +dir+, relative to +dir+, sorted for
  # deterministic diffing/output.
  def relative_files(dir)
    ::Dir.glob("**/*", base: dir).select { |rel_path| ::File.file?(::File.join(dir, rel_path)) }.sort
  end

  # Asserts +output_dir+ (freshly generated) and +fixture_dir+ (hand-authored
  # under examples/) contain the same files with byte-identical contents.
  def assert_matches_fixture(output_dir, fixture_dir)
    actual_files = relative_files(output_dir)
    expected_files = relative_files(fixture_dir)

    extra = actual_files - expected_files
    assert_empty(extra, "generated files not present under #{fixture_dir}: #{extra.join(', ')}")

    missing = expected_files - actual_files
    assert_empty(missing, "#{fixture_dir} files not generated by the template: #{missing.join(', ')}")

    (expected_files & actual_files).each do |rel_path|
      actual = ::File.read(::File.join(output_dir, rel_path))
      expected = ::File.read(::File.join(fixture_dir, rel_path))
      assert_equal(expected, actual, "mismatch for #{rel_path}")
    end
  end

  it "renders output identical to the examples/geometry/doc fixture" do
    ::Dir.mktmpdir do |output_dir|
      generate(output_dir)
      assert_matches_fixture(output_dir, geometry_doc_dir)
    end
  end

  it "renders --markup rdoc output identical to the examples/rdoc/doc fixture" do
    ::Dir.mktmpdir do |output_dir|
      generate_rdoc(output_dir)
      assert_matches_fixture(output_dir, rdoc_doc_dir)
    end
  end
end
