# frozen_string_literal: true

require "helper"
require "tmpdir"

describe "agentdocs template" do
  let(:project_root) { ::File.expand_path("..", __dir__) }
  let(:example_doc_dir) { ::File.join(project_root, "example/doc") }
  let(:example_rdoc_doc_dir) { ::File.join(project_root, "example/rdoc/doc") }

  # Runs from the project root so recorded source paths (used in "Defined in"
  # lines) come out relative, matching the example/doc fixtures.
  def generate(output_dir)
    ::YARD::Registry.clear
    ::Dir.chdir(project_root) do
      files = ::Dir.glob("example/lib/**/*.rb")
      ::YARD::CLI::Yardoc.new.run(
        "--no-yardopts", "--no-save", "--no-stats",
        "-o", output_dir,
        "-t", "default",
        "-f", "agentdocs",
        "--markup", "markdown",
        "--title", "yard-agentdocs example — API Reference",
        "--readme", "example/README.md",
        "--files", "example/docs/point_cloud.md",
        *files
      )
    end
  end

  # A small, separate fixture run with `--markup rdoc`, covering the
  # `:rdoc`-dialect path end to end (see "Docstring markup dialect" in
  # docs/dev/DESIGN.md) without coupling the main markdown-dialect fixture
  # set above to the installed rdoc gem's exact conversion output.
  def generate_rdoc(output_dir)
    ::YARD::Registry.clear
    ::Dir.chdir(project_root) do
      files = ::Dir.glob("example/rdoc/lib/**/*.rb")
      ::YARD::CLI::Yardoc.new.run(
        "--no-yardopts", "--no-save", "--no-stats",
        "-o", output_dir,
        "-t", "default",
        "-f", "agentdocs",
        "--markup", "rdoc",
        "--title", "yard-agentdocs rdoc-dialect fixture — API Reference",
        "--readme", "example/rdoc/README.rdoc",
        *files
      )
    end
  end

  # All regular file paths under +dir+, relative to +dir+, sorted for
  # deterministic diffing/output.
  def relative_files(dir)
    ::Dir.glob("**/*", base: dir).select { |rel_path| ::File.file?(::File.join(dir, rel_path)) }.sort
  end

  # Asserts +output_dir+ (freshly generated) and +fixture_dir+ (hand-authored
  # under example/) contain the same files with byte-identical contents.
  def assert_matches_fixture(output_dir, fixture_dir)
    actual_files = relative_files(output_dir)
    expected_files = relative_files(fixture_dir)

    extra = actual_files - expected_files
    assert_empty(extra, "generated files not present under #{fixture_dir}: #{extra.join(', ')}")

    missing = expected_files - actual_files
    assert_empty(missing, "#{fixture_dir} files not generated by the template: #{missing.join(', ')}")

    (expected_files & actual_files).each do |rel_path|
      actual = ::File.read(::File.join(output_dir, rel_path))
      expected = ::File.read(::File.join(fixture_dir, rel_path))
      assert_equal(expected, actual, "mismatch for #{rel_path}")
    end
  end

  it "renders output identical to the example/doc fixture" do
    ::Dir.mktmpdir do |output_dir|
      generate(output_dir)
      assert_matches_fixture(output_dir, example_doc_dir)
    end
  end

  it "renders --markup rdoc output identical to the example/rdoc/doc fixture" do
    ::Dir.mktmpdir do |output_dir|
      generate_rdoc(output_dir)
      assert_matches_fixture(output_dir, example_rdoc_doc_dir)
    end
  end
end
