# frozen_string_literal: true

require "date"
require "yaml"

module Corpus
  ##
  # Builds the corpus manifest: the durable list of gem names and exact
  # versions that a structural-invariant run documents and checks.
  #
  # The manifest exists so that the corpus is reproducible. Rankings move
  # daily and the service that serves them has no availability guarantee, so
  # a run that re-derived its own gem list would never check the same corpus
  # twice and would stop working the day the service did. Generation is
  # therefore a deliberate, occasional act whose output is committed.
  #
  # ## How the two rankings combine
  #
  # Candidates are taken round-robin by rank — best of the first strategy,
  # best of the second, second-best of the first, and so on — rather than by
  # unioning each strategy's top slice. Build time is what limits this corpus,
  # so `count` has to mean the number of gems you get; a union's size depends
  # on an overlap fraction nobody controls. Round-robin also keeps both
  # strategies materially represented, where a union would let the strategy
  # with the longer reach supply most of the tail.
  #
  # Every selected gem records its rank under *every* strategy that ranked it,
  # not just the one that drew it. That is what makes "which gems does
  # dependents-rank find that downloads-rank misses?" answerable by reading
  # the manifest.
  #
  class ManifestGenerator
    ##
    # How many ranked names to pull from each strategy per gem wanted.
    #
    # Selection discards a lot: duplicates between the two rankings, gems over
    # a family cap, exclusions, and the occasional name that will not resolve.
    # Fetching a multiple of `count` means one query per strategy rather than
    # paging when the discards bite. Four is comfortably past what the caps
    # have ever consumed and still far inside the query's row limit.
    #
    OVERFETCH_FACTOR = 4

    ##
    # @param config [Corpus::Config] Pins, exclusions and family caps.
    # @param ranker [#rank] Supplies ranked gem names per strategy.
    # @param resolver [#resolve] Maps a gem name to its current version.
    # @param count [Integer] How many gems the manifest should name.
    # @param strategies [Array<String>] Ranking strategies, in interleave order.
    # @param window_days [Integer] Trailing window for time-windowed strategies.
    # @param today [Date] Generation date, injectable so output is testable.
    #
    def initialize(config:, ranker:, resolver:, count:, strategies:,
                   window_days:, today: ::Date.today)
      @config = config
      @ranker = ranker
      @resolver = resolver
      @count = count
      @strategies = strategies
      @window_days = window_days
      @today = today
    end

    ##
    # Selects gems and returns the manifest as a plain data structure.
    #
    # @return [Hash] The manifest contents.
    #
    def generate
      @taken = []
      @unresolvable = []
      rankings = fetch_rankings
      pins = select_pins(rankings)
      selected = pins + select_ranked(rankings, pins.size)
      if selected.size < @count
        raise GenerationError,
              "only #{selected.size} of #{@count} gems could be selected; the rankings ran out. " \
              "Raise OVERFETCH_FACTOR or lower --count."
      end
      manifest(selected)
    end

    ##
    # Generates the manifest and writes it to a file, atomically.
    #
    # The write goes to a temporary file in the same directory and is renamed
    # into place, so an interrupted run cannot leave a half-written manifest
    # that later looks like a deliberately smaller corpus.
    #
    # @param path [String] Destination path.
    # @return [Hash] The manifest contents that were written.
    #
    def write(path)
      data = generate
      temp = "#{path}.tmp#{::Process.pid}"
      ::File.write(temp, serialize(data))
      ::File.rename(temp, path)
      data
    ensure
      ::File.unlink(temp) if temp && ::File.exist?(temp)
    end

    ##
    # Renders manifest data as the YAML that gets committed.
    #
    # @param data [Hash] Manifest contents.
    # @return [String] File contents including the generated-file banner.
    #
    def serialize(data)
      <<~BANNER + ::YAML.dump(data)
        # Generated by `toys corpus manifest`. Do not edit.
        #
        # Everything a human decides about this corpus -- pins, exclusions and
        # family caps -- lives in corpus-config.yml and is merged in here on
        # every run. Editing this file by hand loses that edit on the next run.
      BANNER
    end

    ##
    # Raised when a manifest cannot be produced.
    #
    class GenerationError < ::StandardError
    end

    private

    # One ranked list per strategy. The lists are also the reverse lookup that
    # lets a selected gem report its rank under strategies that did not draw
    # it, which is why they are kept whole rather than consumed as they go.
    def fetch_rankings
      @strategies.to_h do |strategy|
        names = @ranker.rank(strategy, limit: @count * OVERFETCH_FACTOR, window_days: @window_days)
        [strategy, names]
      end
    end

    # Pins come first and are exempt from family caps: a pin is an explicit
    # override of what the rankings would have chosen, and a cap silently
    # dropping one would make the override unreliable. Pins do consume
    # `count`, which is a statement about build time and so applies to every
    # gem in the corpus however it got there.
    #
    # A pin that will not resolve is fatal rather than skipped. Someone stated
    # that this gem belongs in the corpus; quietly leaving it out would make
    # the manifest disagree with the config with nothing to show for it.
    def select_pins(rankings)
      if @config.pins.size > @count
        raise GenerationError,
              "#{@config.pins.size} gems are pinned but only #{@count} are wanted"
      end
      @config.pins.map do |name|
        version = @resolver.resolve(name)
        raise GenerationError, "pinned gem #{name.inspect} has no current release" if version.nil?
        record(name, version, rankings, pinned: true)
      end
    end

    # Walks the rankings round-robin until `count` is reached or every list is
    # spent. A pass that selects nothing means all cursors hit the end, which
    # is the only way out other than reaching the target.
    def select_ranked(rankings, already_taken)
      cursors = @strategies.to_h { |strategy| [strategy, 0] }
      family_counts = ::Hash.new(0)
      results = []
      while already_taken + results.size < @count
        progressed = false
        @strategies.each do |strategy|
          break if already_taken + results.size >= @count
          entry = take_next(strategy, rankings, cursors, family_counts)
          next if entry.nil?
          results << entry
          progressed = true
        end
        break unless progressed
      end
      results
    end

    # Advances one strategy's cursor to the next name that is selectable and
    # resolvable, consuming everything it rejects on the way.
    #
    # A name rejected because its family is full is consumed permanently. That
    # is safe only because family counts never decrease, so a family at its
    # cap never reopens -- if caps ever become releasable, this has to become
    # a re-scan instead of a cursor.
    def take_next(strategy, rankings, cursors, family_counts)
      names = rankings[strategy]
      while cursors[strategy] < names.size
        name = names[cursors[strategy]]
        cursors[strategy] += 1
        next unless selectable?(name, family_counts)
        version = @resolver.resolve(name)
        if version.nil?
          @unresolvable << name
          next
        end
        family = @config.family_for(name)
        family_counts[family.name] += 1 if family
        return record(name, version, rankings, pinned: false)
      end
      nil
    end

    def selectable?(name, family_counts)
      return false if @taken.include?(name) || @unresolvable.include?(name)
      return false if @config.excluded?(name)
      family = @config.family_for(name)
      return true if family.nil?
      family_counts[family.name] < family.cap
    end

    # Builds one manifest entry. Raw download and dependent counts are
    # deliberately not recorded: they change every day, so storing them would
    # make every regeneration diff a wall of noise that hides the membership
    # changes the diff exists to show. Rank says everything the count says,
    # ordinally, and is far more stable.
    def record(name, version, rankings, pinned:)
      @taken << name
      entry = {"name" => name, "version" => version}
      entry["pinned"] = true if pinned
      ranks = rankings.filter_map do |strategy, names|
        index = names.index(name)
        [strategy, index + 1] if index
      end.to_h
      entry["ranks"] = ranks unless ranks.empty?
      entry
    end

    # Entries are written alphabetically, not in selection order. Each entry
    # already carries its ranks, so selection order adds nothing the file does
    # not have -- but it would cost a great deal: one gem moving up two ranks
    # would cascade-reorder everything below it, and a regeneration that
    # changed two members would diff as though it changed two hundred.
    def manifest(selected)
      {
        "generated_at" => @today.to_s,
        "window_days" => @window_days,
        "strategies" => @strategies,
        "count" => selected.size,
        "gems" => selected.sort_by { |entry| entry["name"] },
      }
    end
  end
end
