# frozen_string_literal: true

##
# A simple stopwatch that accumulates elapsed time, in seconds.
#
# Defined at the top level (not nested inside any module), to exercise how
# `yard-agentdocs` renders a class that isn't namespaced.
#
# Call {#reset the reset method} to start over.
#
# @note Not thread-safe: concurrent `#add`/`#measure` calls on the same
#   stopwatch can lose updates.
# @todo Support pausing/resuming instead of only accumulating.
#
#   Would also need to decide whether a paused stopwatch's own `#describe`
#   output should say so explicitly, or just look identical to a running
#   one — a second paragraph purely to exercise a multi-paragraph tag
#   (blank line and all) instead of a single wrapped one.
# @api public
#
class Stopwatch
  ##
  # The elapsed time a newly created stopwatch starts at, and the default
  # value `#reset` resets to.
  #
  # @return [Float]
  #
  DEFAULT_ELAPSED = 0.0

  ##
  # The monotonic clock ID used to measure elapsed time in {#measure}.
  #
  # @return [Integer]
  #
  CLOCK = ::Process::CLOCK_MONOTONIC
  private_constant :CLOCK

  ##
  # How many `Stopwatch` instances have been created. YARD registers this as
  # a first-class `classvariable` code object, but `yard-agentdocs` has no
  # section for class variables and deliberately omits them from its
  # output — modern Ruby style avoids `@@` variables, so a class using one
  # doesn't get agent-facing documentation for it. Exercises that omission.
  #
  # @return [Integer]
  #
  @@instance_count = 0

  ##
  # Creates a stopwatch with no elapsed time yet recorded.
  #
  def initialize
    @elapsed = DEFAULT_ELAPSED
    @log_level = "info"
    @rounding_mode = :up
    @label_style = "plain"
    @@instance_count += 1
  end

  class << self
    ##
    # Whether class-level operations should log diagnostic output to
    # `$stderr`. A `class << self`-defined attribute — should behave and
    # render the same as an instance-level `attr_accessor`, just at class
    # scope.
    #
    # @return [Boolean]
    #
    attr_accessor :verbose

    ##
    # The clock's reported resolution, in seconds — how precise
    # {#measure}'s timing can actually be. A `class << self`-defined
    # method — should render identically to `def self.foo`.
    #
    # @return [Float]
    #
    def clock_resolution
      ::Process.clock_getres(CLOCK)
    end

    ##
    # Configures {.verbose} and {.log_target} together in one call.
    #
    # Exercises per-overload `@option`, `@deprecated`, and `@note` — a
    # legacy hash-options call form migrating to a keyword-args one, kept
    # side by side during a deprecation window, the way many gems handled
    # the Ruby 2.7/3.0 keyword-argument separation. No real-world precedent
    # for any of these nested inside a specific `@overload` was found in the
    # gems reviewed so far; included anyway by explicit human decision (see
    # DESIGN.md's per-overload checklist item).
    #
    # @overload configure(opts = {})
    #   The original, hash-based calling form, kept for backward
    #   compatibility.
    #
    #   @deprecated Use the keyword form instead.
    #   @param opts [Hash] the settings to apply
    #   @option opts [Boolean] :verbose (false) whether to log diagnostic output
    #   @option opts [IO] :log_target ($stderr) where to write it
    #   @return [void]
    #
    # @overload configure(verbose: false, log_target: $stderr)
    #   The current, keyword-based calling form.
    #
    #   @note Unlike the hash form, an unrecognized keyword raises
    #     immediately instead of being silently ignored.
    #   @param verbose [Boolean] whether to log diagnostic output
    #   @param log_target [IO] where to write it
    #   @return [void]
    #
    def configure(opts = nil, verbose: false, log_target: $stderr)
      if opts
        verbose = opts.fetch(:verbose, false)
        log_target = opts.fetch(:log_target, $stderr)
      end
      self.verbose = verbose
      self.log_target = log_target
    end

    ##
    # Where {.verbose} diagnostic output is written. `$stderr` until
    # changed.
    #
    # @return [IO]
    #
    def log_target
      @log_target ||= $stderr
    end

    ##
    # Sets {.log_target}. Hand-written instead of `attr_writer` so it can
    # validate — an explicit `def name=(value)` not registered via
    # `attr_*`, exercising a plain assignment method's rendering at class
    # scope (as opposed to `.verbose=`, generated by `attr_accessor` above).
    #
    # @param value [IO] the stream to write diagnostic output to
    # @raise [TypeError] if `value` doesn't respond to `#puts`
    #
    def log_target=(value)
      raise TypeError, "log_target must respond to #puts" unless value.respond_to?(:puts)
      @log_target = value
    end
  end
  self.verbose = false

  ##
  # Adds to the elapsed time.
  #
  # @param seconds [Float] the number of seconds to add
  # @return [Float] the new total elapsed time
  # @api internal
  #
  def add(seconds)
    @elapsed += seconds
  end

  ##
  # Older name for `#add`, from an earlier version of this API.
  #
  # ## Migrating
  #
  # Prefer `#add` in new code. `#accrue` is kept only so callers written
  # against the 1.x API keep working.
  #
  alias_method :accrue, :add

  ##
  # Forwards every argument (and any block) it's called with to {#add},
  # using Ruby's `...` argument-forwarding shorthand.
  #
  # @return [Float] see {#add}
  #
  def add_forwarded(...)
    add(...)
  end

  ##
  # Forwards its arguments and block to {#add}, the same as
  # {#add_forwarded}, but spelled with Ruby's fully anonymous
  # splat/double-splat/block parameters (`*, **, &`) instead of `...`.
  #
  # @return [Float] see {#add}
  #
  def add_forwarded_anon(*, **, &)
    add(*, **, &)
  end

  ##
  # Resets the elapsed time.
  #
  # @param to [Float] the elapsed time to reset to; defaults to
  #   `DEFAULT_ELAPSED`, which returns the stopwatch to its just-created,
  #   zeroed state
  # @param seconds [Float] stale: this method used to take a `seconds`/
  #   `millis` pair, since collapsed into the single `to` argument, but
  #   the old tags were never removed. Exercises a docstring that's fallen
  #   out of sync with its signature — an unmatched-name tag like this one
  #   should be dropped entirely rather than rendered, since it doesn't
  #   correspond to any real parameter
  # @param millis [Integer] stale; see `seconds`
  # @return [Float] the new elapsed time
  #
  def reset(to = DEFAULT_ELAPSED)
    @elapsed = to
  end
  alias_method :restart, :reset
  alias_method :stringify, :to_s

  ##
  # Older name for `#inspect`, from an earlier diagnostics helper. Prefer
  # `#inspect` in new code.
  #
  alias_method :introspect, :inspect

  ##
  # Runs the given block and adds how long it took to this stopwatch's
  # elapsed time.
  #
  # @yield the work to time
  # @yieldreturn [Object] the block's own return value, passed through unchanged
  # @return [Object] the block's return value
  #
  def measure(&block)
    before = current_time
    result = block.call
    @elapsed += current_time - before
    result
  end

  ##
  # Builds a descriptive label for this stopwatch. Combines every parameter
  # shape this format's signature line can render — a required positional
  # argument, an optional positional argument, a splat, a required keyword,
  # an optional keyword, a double-splat, and a block — in one signature,
  # purely to exercise how they assemble together; not a realistic
  # formatting API.
  #
  # @param name [String] the stopwatch's label
  # @param precision [Integer] decimal places to round the elapsed time to
  # @param tags [Array<String>] extra tags to include
  # @param unit [String] the unit label, e.g. `"s"`
  # @param separator [String] the string used to join the tags
  # @param metadata [Hash{Symbol => Object}] arbitrary extra key/value pairs to include
  # @param block [Proc] a block to post-process the label, used instead of it if given
  # @return [String] the assembled label
  #
  def describe(name, precision = 1, *tags, unit:, separator: ", ", **metadata, &block)
    base = "#{name} (#{@elapsed.round(precision)}#{unit})"
    base += " [#{tags.join(separator)}]" unless tags.empty?
    base += " #{metadata}" unless metadata.empty?
    block ? block.call(base) : base
  end

  ##
  # Formats the elapsed time for internal diagnostic tooling. Kept public so
  # other objects in this library can call it directly, but not meant to be
  # part of the stable public API.
  #
  # @private
  # @return [String] the elapsed time, in seconds, as a plain string
  #
  def raw_elapsed_s
    @elapsed.to_s
  end

  ##
  # Compares this stopwatch's elapsed time to another's, per Ruby's `<=>`
  # convention. Doesn't mix in `Comparable`, so this is the only comparison
  # operator available (no `<`, `>`, etc. — see {Geometry::Point}, which
  # makes the same choice).
  #
  # @param other [Stopwatch] the stopwatch to compare to
  # @return [Integer] -1, 0, or 1
  #
  def <=>(other)
    elapsed <=> other.elapsed
  end

  ##
  # A short identifier for this stopwatch, useful for grouping related log
  # entries. `nil` until explicitly set.
  #
  # @return [String, nil]
  #
  def tag
    @tag
  end

  ##
  # Sets {#tag}. Hand-written instead of `attr_writer` so it can
  # validate — an explicit `def name=(value)` not registered via
  # `attr_*`, exercising a plain assignment method's rendering.
  #
  # @param value [String] the new tag; must not be empty
  # @raise [ArgumentError] if `value` is empty
  #
  def tag=(value)
    raise ArgumentError, "tag can't be empty" if value.empty?
    @tag = value
  end

  ##
  # The severity level to log at, e.g. `"debug"`, `"info"`, or `"warn"`.
  # Defaults to `"info"`.
  #
  # Exercises `Docstring#summary`'s abbreviation skip-list: a naive scan
  # would otherwise treat "e.g."'s period as the sentence's end.
  #
  # @return [String]
  #
  attr_accessor :log_level

  ##
  # Which way to round elapsed time when display precision truncates a
  # fractional second, i.e. `:up` or `:down`. Defaults to `:up`.
  #
  # Same skip-list as {#log_level}, but for `"i.e."` instead of `"e.g."` —
  # proves the fix applies to every abbreviation on the list.
  #
  # @return [Symbol]
  #
  attr_accessor :rounding_mode

  ##
  # The formatting style applied when rendering `#tag` for display —
  # `"plain"`, `"bold"`, `"colored"`, etc. Additional styles may be
  # added later.
  #
  # Unlike {#log_level}/{#rounding_mode}, `"etc."` is deliberately not
  # on the skip-list — it can legitimately end a sentence, so this
  # summary should still stop right after it.
  #
  # @return [String]
  #
  attr_accessor :label_style

  protected

  ##
  # The elapsed time, as tracked internally. Exposed to other `Stopwatch`
  # instances (for {#<=>}), but not as a public accessor.
  #
  # @return [Float]
  #
  def elapsed
    @elapsed
  end

  private

  ##
  # The current monotonic clock reading, used to measure elapsed time in
  # {#measure}.
  #
  # @return [Float]
  #
  def current_time
    ::Process.clock_gettime(CLOCK)
  end
end
